# Form implementation generated from reading ui file 'carte_placee.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_carte_placee(object):
    def setupUi(self, carte_placee):
        carte_placee.setObjectName("carte_placee")
        carte_placee.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=carte_placee)
        self.label.setGeometry(QtCore.QRect(50, 70, 291, 141))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(carte_placee)
        QtCore.QMetaObject.connectSlotsByName(carte_placee)

    def retranslateUi(self, carte_placee):
        _translate = QtCore.QCoreApplication.translate
        carte_placee.setWindowTitle(_translate("carte_placee", "Dialog"))
        self.label.setText(_translate("carte_placee", "Carte placée"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    carte_placee = QtWidgets.QDialog()
    ui = Ui_carte_placee()
    ui.setupUi(carte_placee)
    carte_placee.show()
    sys.exit(app.exec())
