# Form implementation generated from reading ui file 'choix.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Choix(object):
    def setupUi(self, Choix):
        Choix.setObjectName("Choix")
        Choix.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=Choix)
        self.label.setGeometry(QtCore.QRect(50, 85, 301, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Choix)
        QtCore.QMetaObject.connectSlotsByName(Choix)

    def retranslateUi(self, Choix):
        _translate = QtCore.QCoreApplication.translate
        Choix.setWindowTitle(_translate("Choix", "Dialog"))
        self.label.setText(_translate("Choix", "choix de la carte"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Choix = QtWidgets.QDialog()
    ui = Ui_Choix()
    ui.setupUi(Choix)
    Choix.show()
    sys.exit(app.exec())
