# Form implementation generated from reading ui file 'fenetre_parametre.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fenetre_parametre(object):
    def setupUi(self, fenetre_parametre):
        fenetre_parametre.setObjectName("fenetre_parametre")
        fenetre_parametre.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=fenetre_parametre)
        self.label.setGeometry(QtCore.QRect(90, 120, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(fenetre_parametre)
        QtCore.QMetaObject.connectSlotsByName(fenetre_parametre)

    def retranslateUi(self, fenetre_parametre):
        _translate = QtCore.QCoreApplication.translate
        fenetre_parametre.setWindowTitle(_translate("fenetre_parametre", "Dialog"))
        self.label.setText(_translate("fenetre_parametre", "fenetre parametre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fenetre_parametre = QtWidgets.QDialog()
    ui = Ui_fenetre_parametre()
    ui.setupUi(fenetre_parametre)
    fenetre_parametre.show()
    sys.exit(app.exec())
