# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from fenetre_parametre import Ui_fenetre_parametre
from choix import Ui_Choix
from carte_placee import Ui_carte_placee

class Ui_Dialog(object):
    def OpenParametres(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_fenetre_parametre()
        self.ui.setupUi(self.window)
        self.window.show()
    def OpenChoix(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Choix()
        self.ui.setupUi(self.window)
        self.window.show()
    def OpenCarte(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_carte_placee()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(969, 808)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(230, 70, 491, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog,clicked = lambda : self.OpenCarte())
        self.pushButton.setGeometry(QtCore.QRect(180, 580, 101, 181))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog, clicked = lambda : self.OpenCarte())
        self.pushButton_2.setGeometry(QtCore.QRect(300, 580, 101, 181))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Dialog, clicked = lambda : self.OpenCarte())
        self.pushButton_3.setGeometry(QtCore.QRect(420, 580, 101, 181))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=Dialog, clicked = lambda : self.OpenCarte())
        self.pushButton_4.setGeometry(QtCore.QRect(540, 580, 101, 181))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=Dialog, clicked = lambda : self.OpenCarte())
        self.pushButton_5.setGeometry(QtCore.QRect(660, 580, 101, 181))
        self.pushButton_5.setObjectName("pushButton_5")
        self.Parametres = QtWidgets.QPushButton(parent=Dialog , clicked = lambda : self.OpenParametres())
        self.Parametres.setGeometry(QtCore.QRect(10, 10, 93, 61))
        self.Parametres.setObjectName("Parametres")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(770, 90, 171, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Carte_1"))
        self.pushButton_2.setText(_translate("Dialog", "Carte_2"))
        self.pushButton_3.setText(_translate("Dialog", "Carte_3"))
        self.pushButton_4.setText(_translate("Dialog", "Carte_4"))
        self.pushButton_5.setText(_translate("Dialog", "Carte_5"))
        self.Parametres.setText(_translate("Dialog", "Parametres"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
