# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import numpy as np

class Ui_Dialog(object):
    def setupUi(self, Dialog, n=10):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1057, 835)
        self.n_ligne = n
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(180, 90, 491, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grille_jeu = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grille_jeu.setContentsMargins(0, 0, 0, 0)
        self.grid = np.array( [[None for i in range(n)] for j in range(n)])
        for i in range(n) : 
            for j in range(n) :
                self.grid[i,j] = QtWidgets.QLabel(parent=self.gridLayoutWidget)
                self.grid[i,j].setObjectName(f"c{i}{j}")
                self.grille_jeu.addWidget(self.grid[i][j], i, j, 1, 1)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        for i in range(self.n_ligne) : 
            for j in range(self.n_ligne) : 
                self.grid[i,j].setText(_translate("Dialog", f"c{i}{j}"))


if __name__ == "__main__" : 
    import sys 
    app = QtWidgets.QApplication(sys.argv) 
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog,7) 
    Dialog.show() 
    sys.exit(app.exec())